from django.urls import path
from matrix_web import views
from .views import MatrixView, MatrixDetailView, ProfileView, ProfileDetailView, MatrixExportView, MatrixImportView, ProfileExportView, ProfileImportView, LicenseAuthView

urlpatterns = [
    path('matrixes/', MatrixView.as_view(), name="matrix"),
    path('matrix/', MatrixDetailView.as_view(), name="matrix_detail"),
    path('profiles/', ProfileView.as_view(), name="profile"),
    path('profile/', ProfileDetailView.as_view(), name="profile_detail"),
    path('matrix_export/', MatrixExportView.as_view(), name="matrix_export"),
    path('matrix_import/', MatrixImportView.as_view(), name="matrix_import"),
    path('profile_export/', ProfileExportView.as_view(), name="profile_export"),
    path('profile_import/', ProfileImportView.as_view(), name="profile_import"),
    path('license_auth/', LicenseAuthView.as_view(), name="license_auth"),
    path('matrix/<int:matrix_id>/update-names/', views.matrix_update_names, name='matrix_update_names'),
    path('save-layout/', views.save_monitor_layout, name='save_monitor_layout'),
    path('get-layout/<int:matrix_id>/', views.get_monitor_layout, name='get_monitor_layout'),
    path('reset-layout/', views.reset_monitor_layout, name='reset_monitor_layout'),
    path('toggle-visibility/', views.toggle_monitor_visibility, name='toggle_monitor_visibility'),
    path('debug-layout-status/', views.debug_layout_status, name='debug_layout_status'),  # 개발용
    path('check_session_time/', views.check_session_time, name='check_session_time'),
    path('system_logout/', views.system_logout, name='system_logout'),
    path('system_password/', views.system_password, name='system_password'),
    path('verify_system_password/', views.verify_system_password, name='verify_system_password'),
    path('system_template/on_device/', views.on_device, name='on_device'),
    path('setup_ip_permission/', views.setup_ip_permission, name='setup_ip_permission'),
    path('remove_ip_permission/', views.remove_ip_permission, name='remove_ip_permission'),
    path('get_device_names/', views.get_device_names, name='get_device_names'),
    path('update_device_name/', views.update_device_name, name='update_device_name'),
    path('profile-order', views.profile_order, name='profile_order'),
    path('scan_kvm_devices/', views.scan_kvm_devices, name='scan_kvm_devices'),
    path('change_hardware_ip/', views.change_hardware_ip, name='change_hardware_ip'),
    path('change_rpi_ip/', views.change_rpi_ip_view, name='change_rpi_ip'),
    path('control/', views.control, name='control'),
    path('kvm/', views.kvm, name='kvm'),
    path('control_all/', views.control_all, name='control_all'),
    path('change_rpi_ip/', views.change_rpi_ip_view, name='change_rpi_ip'),
    path('get_rpi_ip/', views.get_rpi_ip, name='get_rpi_ip'),
    path('api/check_connection/', views.check_hardware_connection, name='check_hardware_connection'),
    path('api/hardware_status/', views.get_hardware_status, name='get_hardware_status'),
]