# Generated by Django 3.2 on 2021-04-12 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('input_a', models.CharField(default='01', max_length=50)),
                ('input_b', models.CharField(default='02', max_length=50)),
                ('input_c', models.CharField(default='03', max_length=50)),
                ('input_d', models.CharField(default='04', max_length=50)),
                ('input_e', models.CharField(default='05', max_length=50)),
                ('input_f', models.CharField(default='06', max_length=50)),
                ('input_g', models.CharField(default='07', max_length=50)),
                ('input_h', models.CharField(default='08', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrixes', related_query_name='matrix', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
