# Generated by Django 3.2 on 2021-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
