# Generated by Django 3.2 on 2021-04-16 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix_web', '0003_auto_20210415_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', related_query_name='profile', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MatrixSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_a', models.CharField(default='01', max_length=50)),
                ('input_b', models.CharField(default='02', max_length=50)),
                ('input_c', models.CharField(default='03', max_length=50)),
                ('input_d', models.CharField(default='04', max_length=50)),
                ('input_e', models.CharField(default='05', max_length=50)),
                ('input_f', models.CharField(default='06', max_length=50)),
                ('input_g', models.CharField(default='07', max_length=50)),
                ('input_h', models.CharField(default='08', max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_sets', related_query_name='matrix_set', to='matrix_web.matrix')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sets', related_query_name='profile_set', to='matrix_web.profile')),
            ],
        ),
    ]
