# Generated by Django 3.2 on 2021-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0005_auto_20210426_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
