# Generated by Django 3.2 on 2021-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0006_matrix_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='connect_main',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
