# Generated by Django 3.2 on 2021-05-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0007_matrix_connect_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrix',
            old_name='connect_main',
            new_name='main_connect',
        ),
    ]
