# Generated by Django 3.2 on 2021-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0008_rename_connect_main_matrix_main_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='main_connect',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
