# Generated by Django 3.2 on 2021-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0010_matrixsetting_input_kvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='kvm_ip_address2',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
