# Generated by Django 3.2 on 2021-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0011_matrix_kvm_ip_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='kvm_ip_address2',
            field=models.GenericIPAddressField(blank=True, default=' ', null=True),
        ),
    ]
