# Generated by Django 3.2 on 2022-03-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0017_auto_20210722_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to='Uploaded Files/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
