# Generated by Django 3.2 on 2024-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0018_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='input_i',
            field=models.CharField(default='09', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_j',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_k',
            field=models.CharField(default='11', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_l',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_m',
            field=models.CharField(default='13', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_n',
            field=models.CharField(default='14', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_o',
            field=models.CharField(default='15', max_length=50),
        ),
        migrations.AddField(
            model_name='matrix',
            name='input_p',
            field=models.CharField(default='16', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_i',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_j',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_k',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_l',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_m',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_n',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_o',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='matrixsetting',
            name='input_p',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
