# Generated by Django 4.2 on 2025-09-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0020_devicenameconfig_monitorlayout_profileorderconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceNameConfig',
        ),
    ]
