# Generated by Django 3.2 on 2025-11-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to='Uploaded Files/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('monitor_names', models.JSONField(blank=True, default=list, verbose_name='모니터 이름들')),
                ('device_names', models.JSONField(blank=True, default=list, verbose_name='디바이스 이름들')),
                ('matrix_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('kvm_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('kvm_ip_address2', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('main_connect', models.IntegerField(blank=True, default=0, null=True)),
                ('input_a', models.CharField(default='01', max_length=50)),
                ('input_b', models.CharField(default='02', max_length=50)),
                ('input_c', models.CharField(default='03', max_length=50)),
                ('input_d', models.CharField(default='04', max_length=50)),
                ('input_e', models.CharField(default='05', max_length=50)),
                ('input_f', models.CharField(default='06', max_length=50)),
                ('input_g', models.CharField(default='07', max_length=50)),
                ('input_h', models.CharField(default='08', max_length=50)),
                ('input_i', models.CharField(default='09', max_length=50)),
                ('input_j', models.CharField(default='10', max_length=50)),
                ('input_k', models.CharField(default='11', max_length=50)),
                ('input_l', models.CharField(default='12', max_length=50)),
                ('input_m', models.CharField(default='13', max_length=50)),
                ('input_n', models.CharField(default='14', max_length=50)),
                ('input_o', models.CharField(default='15', max_length=50)),
                ('input_p', models.CharField(default='16', max_length=50)),
                ('kvm_input', models.CharField(blank=True, default='01', max_length=50, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='admin123', max_length=255)),
                ('description', models.CharField(blank=True, default='시스템 관리 비밀번호', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '시스템 비밀번호',
                'verbose_name_plural': '시스템 비밀번호',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_order_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_a', models.CharField(default='00', max_length=50)),
                ('input_b', models.CharField(default='00', max_length=50)),
                ('input_c', models.CharField(default='00', max_length=50)),
                ('input_d', models.CharField(default='00', max_length=50)),
                ('input_e', models.CharField(default='00', max_length=50)),
                ('input_f', models.CharField(default='00', max_length=50)),
                ('input_g', models.CharField(default='00', max_length=50)),
                ('input_h', models.CharField(default='00', max_length=50)),
                ('input_i', models.CharField(default='00', max_length=50)),
                ('input_j', models.CharField(default='00', max_length=50)),
                ('input_k', models.CharField(default='00', max_length=50)),
                ('input_l', models.CharField(default='00', max_length=50)),
                ('input_m', models.CharField(default='00', max_length=50)),
                ('input_n', models.CharField(default='00', max_length=50)),
                ('input_o', models.CharField(default='00', max_length=50)),
                ('input_p', models.CharField(default='00', max_length=50)),
                ('input_kvm', models.CharField(default='00', max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_sets', related_query_name='matrix_set', to='matrix_web.matrix')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sets', related_query_name='profile_set', to='matrix_web.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceNameConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('hardware', '하드웨어'), ('server', '서버')], max_length=50)),
                ('device_name', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorLayout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monitor_position', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('row_position', models.IntegerField(default=1)),
                ('col_position', models.IntegerField(default=1)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix_web.matrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'matrix', 'monitor_position')},
            },
        ),
        migrations.AddConstraint(
            model_name='matrixsetting',
            constraint=models.UniqueConstraint(fields=('profile', 'matrix'), name='uq_profile_matrix'),
        ),
        migrations.AlterUniqueTogether(
            name='devicenameconfig',
            unique_together={('user', 'device_type')},
        ),
    ]
