# Generated by Django 3.2 on 2025-11-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0002_add_16port_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '문서', 'verbose_name_plural': '문서들'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': '라이센스', 'verbose_name_plural': '라이센스들'},
        ),
        migrations.AlterModelOptions(
            name='matrix',
            options={'verbose_name': '매트릭스 장비', 'verbose_name_plural': '매트릭스 장비들'},
        ),
        migrations.AlterModelOptions(
            name='matrixsetting',
            options={'verbose_name': '매트릭스 설정', 'verbose_name_plural': '매트릭스 설정들'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['order', 'id'], 'verbose_name': '프로필', 'verbose_name_plural': '프로필들'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': '유저 권한', 'verbose_name_plural': '유저 권한들'},
        ),
        migrations.AlterField(
            model_name='devicenameconfig',
            name='device_name',
            field=models.CharField(default='', help_text='표시할 장비 이름', max_length=200),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='device_names',
            field=models.JSONField(blank=True, default=list, help_text='16개 디바이스의 이름 목록', verbose_name='디바이스 이름들'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='kvm_input',
            field=models.CharField(blank=True, default='01', help_text='현재 선택된 KVM 입력', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='monitor_names',
            field=models.JSONField(blank=True, default=list, help_text='16개 모니터의 이름 목록', verbose_name='모니터 이름들'),
        ),
        migrations.AlterField(
            model_name='monitorlayout',
            name='col_position',
            field=models.IntegerField(default=1, help_text='1~8 (좌우 열)'),
        ),
        migrations.AlterField(
            model_name='monitorlayout',
            name='display_order',
            field=models.IntegerField(default=0, help_text='화면상 표시 순서'),
        ),
        migrations.AlterField(
            model_name='monitorlayout',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='숨김/표시 여부'),
        ),
        migrations.AlterField(
            model_name='monitorlayout',
            name='monitor_position',
            field=models.IntegerField(help_text='1~16 (실제 모니터 포트 번호)'),
        ),
        migrations.AlterField(
            model_name='monitorlayout',
            name='row_position',
            field=models.IntegerField(default=1, help_text='1 or 2 (상하 행)'),
        ),
        migrations.AlterField(
            model_name='profileorderconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profileorderconfig',
            name='order',
            field=models.JSONField(blank=True, default=list, help_text='프로필 ID 순서 리스트'),
        ),
        migrations.AlterField(
            model_name='systempassword',
            name='password',
            field=models.CharField(default='admin123', help_text='시스템 관리자 비밀번호', max_length=255),
        ),
        migrations.AlterModelTable(
            name='document',
            table='matrix_web_document',
        ),
        migrations.AlterModelTable(
            name='license',
            table='matrix_web_license',
        ),
        migrations.AlterModelTable(
            name='matrix',
            table='matrix_web_matrix',
        ),
        migrations.AlterModelTable(
            name='matrixsetting',
            table='matrix_web_matrixsetting',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='matrix_web_profile',
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='matrix_web_userpermission',
        ),
    ]
