# Generated by Django 3.2 on 2025-11-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0003_add_profile_order'),
        ('matrix_web', '0003_auto_20251117_0033'),
    ]

    operations = [
    ]
