# Generated by Django 3.2 on 2025-11-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0004_merge_0003_add_profile_order_0003_auto_20251117_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필들'},
        ),
    ]
