# Generated by Django 3.2 on 2021-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0004_auto_20210416_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrix',
            old_name='ip_address',
            new_name='matrix_ip_address',
        ),
        migrations.AddField(
            model_name='matrix',
            name='kvm_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
