# Generated by Django 3.2 on 2025-11-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='비디오월 이름')),
                ('start_x', models.IntegerField(default=0, verbose_name='시작 X좌표')),
                ('start_y', models.IntegerField(default=0, verbose_name='시작 Y좌표')),
                ('end_x', models.IntegerField(default=0, verbose_name='끝 X좌표')),
                ('end_y', models.IntegerField(default=0, verbose_name='끝 Y좌표')),
                ('input_source', models.IntegerField(default=1, verbose_name='입력 소스')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_walls', to='matrix_web.matrix', verbose_name='매트릭스 장비')),
            ],
            options={
                'verbose_name': '비디오월',
                'verbose_name_plural': '비디오월들',
                'db_table': 'matrix_web_videowall',
                'ordering': ['-created_date'],
            },
        ),
    ]
