# Generated by Django 3.2 on 2021-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0009_alter_matrix_main_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixsetting',
            name='input_kvm',
            field=models.CharField(default='01', max_length=50),
        ),
    ]
