# Generated by Django 3.2 on 2021-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0012_alter_matrix_kvm_ip_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='kvm_ip_address2',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
