# Generated by Django 3.2 on 2021-07-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0014_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
