# Generated by Django 3.2 on 2021-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_web', '0016_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_a',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_b',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_c',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_d',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_e',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_f',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_g',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_h',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixsetting',
            name='input_kvm',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
